[package]
name = "ectool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crosec = { version = "0.1.0", path = "../crosec" }
seahorse = "2.2.0"
